### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by dpgraham4401** [dfunckt/django-rules#191]
The "Django Documentation" hyperlink in the [using the class based view mixin](https://github.com/dfunckt/django-rules?tab=readme-ov-file#using-the-class-based-view-mixin) section is pointing to a non-existent page.

**Comment by dfunckt** [comment]
That’s likely because the link points to docs for Django 1.9, which is a very old version and may been taken down. This link, even though it still has the same problem of hardcoding a version, is currently valid: https://docs.djangoproject.com/en/5.0/topics/auth/default/#limiting-access-to-logged-in-users

I’ll make a PR as soon as I get the chance unless someone else beats me to it.

**Comment by dpgraham4401** [comment]
Instead of hardcoding a version in the URL path, we can use 'stable'. I made a PR. Thanks for being so responsive!
