### ISSUE TITLE
How to use PermissionRequiredMixin

### ISSUE THREAD

**Issue by protactinium** [dfunckt/django-rules#21]
I have start implementing django-rules to my application and I would like to know how can I integrate the permission backend with CBVs in django.

My settings are:
```
AUTHENTICATION_BACKENDS = ( 'account.auth_backends.EmailAuthenticationBackend',
                            'rules.permissions.ObjectPermissionBackend',
                            'django.contrib.auth.backends.ModelBackend')
INSTALLED_APPS = (
    ....,
    'rules.apps.AutodiscoverRulesConfig',
    ...,)
```
**views.py**
```
class BookEditView(SuccessMessageMixin, PermissionRequiredMixin, UpdateView):
    model = Book
    template_name = 'book.html'
    form_class = BookFormSettings

    success_message = "%(title)s was created successfully"

    ### PermissionRequiredMixin settings
    permission_required = 'books.change_course'
```
**rules.py**
```
@predicate
def is_author(user, course):
    return book.author == user

add_perm('books.change_book', is_author)
```

If this does not work, what are the best practices to integrate django-rules through views.

Thanks.

**Comment by dfunckt** [comment]
I'm guessing the PermissionRequiredMixin is from django-braces? There's a PR that extends this mixin to work with object permissions -- #17. You might want to try that. Otherwise it shouldn't be very difficult to override 'dispatch()' yourself and handle permissions. I personally use functional views and check permissions in the view manually.

**Comment by protactinium** [comment]
Thank you for the reply. I chose to use a functional view as it is much cleaner to handle complex logic
