### ISSUE TITLE
Does django-rules work with django rest framework viewsets?

### ISSUE THREAD

**Issue by limbera** [dfunckt/django-rules#56]
Hi, 

I am trying to integrate rules with DRF's viewsets but I keep getting an `AttributeError: 'OrgViewSet' object has no attribute 'request'`

Here is my viewset code:

```python
class OrgViewSet(PermissionRequiredMixin,
                 mixins.ListModelMixin,
                 viewsets.GenericViewSet):
    permission_required = CHANGE_ORG
    queryset = Org.objects.all()
    serializer_class = OrgSerializer

```

Here is the stack trace
```python
Internal Server Error: /orgs/
Traceback (most recent call last):
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 90, in dispatch
    if not self.has_permission():
  File "/Users/dre/code/treebeard/venv/lib/python3.6/site-packages/rules/contrib/views.py", line 51, in has_permission
    return self.request.user.has_perms(perms, obj)
AttributeError: 'OrgViewSet' object has no attribute 'request'
```

Any help would be greatly appreciated.

**Comment by dfunckt** [comment]
@limbera I wouldn't expect the `PermissionRequiredMixin` to be compatible with DRF views out of the box -- AFAIK DRF's view hierarchy is completely separate to Django's and handles the request itself. You are probably better off trying to hook `rules` into DRF's permission system, rather than reusing the mixin directly.

**Comment by jberends** [comment]
We use a combination of DRF with dry-rest-permissions (https://github.com/dbkaplan/dry-rest-permissions) and incorporate django-rules as predicates which are checked in the model permission checker methods. This works like a charm. 

```python
#models.py
class ModelA(Models):
    some_field = ....

    @static_method
    def has_read_permission(request)
        return request.user.has_perm("a_model:read_permission", request)
```
```python
# rules.py
add_perm("a_model:read_permission", is_superuser | is_authenticated & is_group_member('SomeGroup'))
```

**Comment by escodebar** [comment]
As you may have noticed `rules.contrib.views.PermissionRequiredMixin` does not work with `rest_framework.views.APIView`.

As you can see from django's `PermissionRequiredMixin`, the [authorization process starts](https://github.com/django/django/blob/3576bfe07c3c541b6ecd97d56daad0cf3d3f45fc/django/contrib/auth/mixins.py#L82-L85) with `self.has_permission()`, which is not present in the REST framework's `APIView`. The `APIView` checks for permission with [`self.check_permissions(request)`](https://github.com/encode/django-rest-framework/blob/1c9ad52cb6105c442b48fab2e2114969729b0ed9/rest_framework/views.py#L322-L331).

By implementing the logic of `has_permission` in `check_permissions` I was able to write a [mixin](https://github.com/escodebar/django-rules/commit/81f0085a856106567248700d0e6c9cd7910985b8) which allows to use rules with django rest framework API views.

**Comment by escodebar** [comment]
@dfunckt: I'm working on the `PermissionRequiredMixin` for the django REST framework API views.
I wish to make a pull request soon.
Take a look at my branch and tell me, if you wish me to add / change tests (or improve commit messages).
https://github.com/escodebar/django-rules/tree/pe-add_perm_mixin_for_rest_api_view

**Comment by dfunckt** [comment]
@escodebar hey, thanks for your work. DRF has its own permission system, that's completely separate from Django's. I know integration of rules with DRF is going to be very useful but I don't think it belongs into rules' core.

Seeing your work. given the functionality is completely additive and requires no changes to rules core in order to work, it should be trivial to make a separate package with the mixin and related tests. I'd happily link to that project from the README (and leave this ticket open as well, like, forever) so it's discoverable but I'm not inclined to accept this (or any other DRF-integration effort) into core.

**Comment by escodebar** [comment]
@dfunckt: thank **you** for creating such a nice and tidy permission framework!

**Comment by escodebar** [comment]
@dfunckt: it's ready - https://github.com/escodebar/django-rest-framework-rules

**Comment by escodebar** [comment]
@limbera: It works now with the `PermissionRequiredMixin` of django-rest-framework-rules

``` python
from rest_framework_rules.mixins import PermissionRequiredMixin

class OrgViewSet(PermissionRequiredMixin,
                 mixins.ListModelMixin,
                 viewsets.GenericViewSet):
    permission_required = CHANGE_ORG
    queryset = Org.objects.all()
    serializer_class = OrgSerializer
```

See the README or the tests in django-rest-framework-rules for further examples of how to use django-rest-framework-rules.

**Comment by dfunckt** [comment]
@escodebar, thanks, this looks great 👍

Two quick bits of feedback: I think it'd be nice to have a complete example that shows how one would setup a couple of predicates and rules before showing how `django-rest-framework-rules`  is used with DRF, as it now reads somewhat disconnected.

The other is that the project looks like it's a fork of rules even though it shares no code and it properly brings in rules as a dependency, building extra functionality upon it. I'm really not sure if there's a way to resolve this, just saying because I think it's going to confuse a few people trying to use `django-rest-framework-rules`.

**Comment by escodebar** [comment]
@dfunckt: good point. I'll do the "unfork" this weekend.
I'll also add some description on how to define rules.
I hope you don't mind if I just copy-paste parts of your README for this.

**Comment by escodebar** [comment]
`django-rules` works with django REST framework viewsets using the `django-rest-framework-rules` package.

lnstallation and usage are documented in `django-rest-framework-rules`' README, further examples can be found in `django-rest-framework-rules`' tests.

@dfunckt: I guess, that you can close this issue now.

**Comment by dfunckt** [comment]
`rules` now has built-in support for Django Rest Framework (contributed by @efficiosoft in #100). See here for docs on the feature: https://github.com/dfunckt/django-rules#permissions-in-django-rest-framework

DRF support ties well with the newly-added support for automatic permissions for models -- see https://github.com/dfunckt/django-rules#permissions-in-models (also by @efficiosoft, in #99)

All in all, I think `rules` now integrates well with DRF -- let me know of any feedback you may have.
