### ISSUE TITLE
Creating a queryset from rules

### ISSUE THREAD

**Issue by guettli** [dfunckt/django-rules#80]
How can I create queryset which filters according to rules?

Use case: I have a issue tracking system each issue is an instance of Issue (which inherits from models.Model).

I have rules which allow access to the issues.

Now I want a queryset of all issues which are allowed to be seen by user X.

Can you follow my use case?

Do you have a clue how to get this done?

**Comment by dfunckt** [comment]
I know this is much wanted but I'm afraid it's not possible to implement without `rules` becoming something else entirely. TBH I don't even see a way to translate arbitrary code (i.e. predicates) to Queryset filters. Closing, because this functionality can be implemented in an external package and, as explained in https://github.com/dfunckt/django-rules/issues/40#issuecomment-246946913, I'd be happy to extend `rules` with appropriate hooks if needed to accommodate the use case.

**Comment by guettli** [comment]
Thank you very much for the clear statement.
